FROM golang:alpine as builder

COPY . /app

WORKDIR /app

RUN go mod download
RUN GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./cmd/server/main.go

FROM scratch

COPY --from=builder /app/server /app/main
COPY --from=builder /app/config.json /app/config.json

EXPOSE 12012

ENTRYPOINT ["/app/main"]