FROM golang:alpine as builder

COPY . /app

WORKDIR /app/cmd/server

RUN go mod download

RUN go build -o server

FROM scratch

COPY --from=builder /app/cmd/server/server /app/main
COPY --from=builder /app/config.json /app/config.json

EXPOSE 12012

ENTRYPOINT ["/app/main"]