FROM golang:alpine as builder

COPY . /app

WORKDIR /app/cmd/client

RUN go build -o client

FROM scratch

COPY --from=builder /app/cmd/client/client /app/main
COPY --from=builder /app/config.json /app/config.json

ENTRYPOINT ["/app/main"]
